name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build the site
        run: mkdocs build

      - name: Compress site artifact
        run: tar -czf site.tar.gz -C site .

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: site.tar.gz

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Download and extract site artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Extract site artifact
        run: tar -xzf site.tar.gz

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
